---
- name: "My first playbook"
  hosts: my_machines

  tasks:
  - name: "Install apache webserver"
    package:
      name: "{{ apache_package }}"
      state: "present"
    become: True

  - name: "Start apache webserver"
    service:
      name: "{{ apache.service }}"
      state: "started"
    become: True
...
